In [1]:
import pandas as pd
import numpy as np
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels)  = mnist.load_data()

C:\Users\HP\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


11493376/11490434 [==============================] - 117s 10us/step


In [2]:
print("Train Image shape: " , train_images.shape)
print("Len of train labels: ", len(train_labels))
train_labels

Train Image shape:  (60000, 28, 28)
Len of train labels:  60000


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [3]:
print("test Image shape: " , test_images.shape)
print("Len of train labels: ", len(test_labels))
train_labels

test Image shape:  (10000, 28, 28)
Len of train labels:  10000


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [4]:
from keras import models
from keras import layers
network = models.Sequential()
network.add(layers.Dense(512,activation = 'relu' ,input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))

In [5]:
network.compile(optimizer='rmsprop',
               loss= 'categorical_crossentropy',
               metrics= ['accuracy'])

In [6]:
digit = train_images[4]
import matplotlib.pyplot as plt
plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

In [7]:
train_images = train_images.reshape((60000, 28*28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255
train_images.size

47040000

In [8]:
from keras.utils import to_categorical 
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [9]:
network.fit(train_images, train_labels, epochs=5, batch_size=130)

Epoch 1/5
60000/60000 [==============================] - 11s 186us/step - loss: 0.2548 - acc: 0.9273
Epoch 2/5
60000/60000 [==============================] - 8s 139us/step - loss: 0.1033 - acc: 0.9693
Epoch 3/5
60000/60000 [==============================] - 8s 132us/step - loss: 0.0680 - acc: 0.9793  - ETA: 1s - lo
Epoch 4/5
60000/60000 [==============================] - 8s 133us/step - loss: 0.0497 - acc: 0.9845
Epoch 5/5
60000/60000 [==============================] - 8s 140us/step - loss: 0.0371 - acc: 0.9887


In [10]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 2s 198us/step


In [11]:
print("Accuracy : " , test_acc , "\n Test Loss Value: " , test_loss)

Accuracy :  0.9811 
 Test Loss Value:  0.06490714811999351


In [12]:
digit = train_images[0]
digit.shape
p=network.predict(test_images[0:1], verbose=1)
p

1/1 [==============================] - 1s 569ms/step


array([[2.17842278e-09, 7.00132313e-12, 1.71484214e-06, 1.03160528e-05,
        7.84529031e-14, 3.06436698e-09, 2.59616678e-15, 9.99987841e-01,
        1.06871685e-08, 1.41257814e-07]], dtype=float32)